/**
 * Lagrello API
 * API specification for Lagrello, a simple to use authentication service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@lagrello.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ActivateTenantRequest model module.
 * @module model/ActivateTenantRequest
 * @version 1.0.0
 */
class ActivateTenantRequest {
    /**
     * Constructs a new <code>ActivateTenantRequest</code>.
     * @alias module:model/ActivateTenantRequest
     * @param companyName {String} The full name of your company.
     * @param companyAddress {String} The first line of the address for your company.
     * @param companyCity {String} The city in which the address is located.
     * @param companyPostalCode {String} The postal code for the address.
     * @param companyCountry {String} The country in which the address is located. This should be given as an ISO 3361-1 country code (two letter abbreviation).
     * @param companyOrgNumber {String} Your company's organization number.
     * @param companyVATNumber {String} A value added tax identification number, identifier used in many countries, including the countries of the European Union, for value added tax purposes.
     */
    constructor(companyName, companyAddress, companyCity, companyPostalCode, companyCountry, companyOrgNumber, companyVATNumber) { 
        
        ActivateTenantRequest.initialize(this, companyName, companyAddress, companyCity, companyPostalCode, companyCountry, companyOrgNumber, companyVATNumber);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, companyName, companyAddress, companyCity, companyPostalCode, companyCountry, companyOrgNumber, companyVATNumber) { 
        obj['companyName'] = companyName;
        obj['companyAddress'] = companyAddress;
        obj['companyCity'] = companyCity;
        obj['companyPostalCode'] = companyPostalCode;
        obj['companyCountry'] = companyCountry;
        obj['companyOrgNumber'] = companyOrgNumber;
        obj['companyVATNumber'] = companyVATNumber;
    }

    /**
     * Constructs a <code>ActivateTenantRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ActivateTenantRequest} obj Optional instance to populate.
     * @return {module:model/ActivateTenantRequest} The populated <code>ActivateTenantRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ActivateTenantRequest();

            if (data.hasOwnProperty('companyName')) {
                obj['companyName'] = ApiClient.convertToType(data['companyName'], 'String');
            }
            if (data.hasOwnProperty('companyAddress')) {
                obj['companyAddress'] = ApiClient.convertToType(data['companyAddress'], 'String');
            }
            if (data.hasOwnProperty('companyCity')) {
                obj['companyCity'] = ApiClient.convertToType(data['companyCity'], 'String');
            }
            if (data.hasOwnProperty('companyPostalCode')) {
                obj['companyPostalCode'] = ApiClient.convertToType(data['companyPostalCode'], 'String');
            }
            if (data.hasOwnProperty('companyCountry')) {
                obj['companyCountry'] = ApiClient.convertToType(data['companyCountry'], 'String');
            }
            if (data.hasOwnProperty('companyOrgNumber')) {
                obj['companyOrgNumber'] = ApiClient.convertToType(data['companyOrgNumber'], 'String');
            }
            if (data.hasOwnProperty('companyVATNumber')) {
                obj['companyVATNumber'] = ApiClient.convertToType(data['companyVATNumber'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The full name of your company.
 * @member {String} companyName
 */
ActivateTenantRequest.prototype['companyName'] = undefined;

/**
 * The first line of the address for your company.
 * @member {String} companyAddress
 */
ActivateTenantRequest.prototype['companyAddress'] = undefined;

/**
 * The city in which the address is located.
 * @member {String} companyCity
 */
ActivateTenantRequest.prototype['companyCity'] = undefined;

/**
 * The postal code for the address.
 * @member {String} companyPostalCode
 */
ActivateTenantRequest.prototype['companyPostalCode'] = undefined;

/**
 * The country in which the address is located. This should be given as an ISO 3361-1 country code (two letter abbreviation).
 * @member {String} companyCountry
 */
ActivateTenantRequest.prototype['companyCountry'] = undefined;

/**
 * Your company's organization number.
 * @member {String} companyOrgNumber
 */
ActivateTenantRequest.prototype['companyOrgNumber'] = undefined;

/**
 * A value added tax identification number, identifier used in many countries, including the countries of the European Union, for value added tax purposes.
 * @member {String} companyVATNumber
 */
ActivateTenantRequest.prototype['companyVATNumber'] = undefined;






export default ActivateTenantRequest;

