/**
 * Lagrello API
 * API specification for Lagrello, a simple to use authentication service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@lagrello.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateTenantRequest model module.
 * @module model/CreateTenantRequest
 * @version 1.0.0
 */
class CreateTenantRequest {
    /**
     * Constructs a new <code>CreateTenantRequest</code>.
     * @alias module:model/CreateTenantRequest
     * @param tenantName {String} The name of the tenant should preferably be the name of your organization/company. Does not need to be but your end users will see this name.
     * @param adminEmail {String} Email to the person that will be tenant admin.
     */
    constructor(tenantName, adminEmail) { 
        
        CreateTenantRequest.initialize(this, tenantName, adminEmail);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, tenantName, adminEmail) { 
        obj['tenantName'] = tenantName;
        obj['adminEmail'] = adminEmail;
    }

    /**
     * Constructs a <code>CreateTenantRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateTenantRequest} obj Optional instance to populate.
     * @return {module:model/CreateTenantRequest} The populated <code>CreateTenantRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateTenantRequest();

            if (data.hasOwnProperty('tenantName')) {
                obj['tenantName'] = ApiClient.convertToType(data['tenantName'], 'String');
            }
            if (data.hasOwnProperty('adminEmail')) {
                obj['adminEmail'] = ApiClient.convertToType(data['adminEmail'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The name of the tenant should preferably be the name of your organization/company. Does not need to be but your end users will see this name.
 * @member {String} tenantName
 */
CreateTenantRequest.prototype['tenantName'] = undefined;

/**
 * Email to the person that will be tenant admin.
 * @member {String} adminEmail
 */
CreateTenantRequest.prototype['adminEmail'] = undefined;






export default CreateTenantRequest;

