/**
 * Lagrello API
 * API specification for Lagrello, a simple to use authentication service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@lagrello.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Paging model module.
 * @module model/Paging
 * @version 1.0.0
 */
class Paging {
    /**
     * Constructs a new <code>Paging</code>.
     * @alias module:model/Paging
     * @param previous {String} 
     * @param next {String} 
     */
    constructor(previous, next) { 
        
        Paging.initialize(this, previous, next);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, previous, next) { 
        obj['previous'] = previous;
        obj['next'] = next;
    }

    /**
     * Constructs a <code>Paging</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Paging} obj Optional instance to populate.
     * @return {module:model/Paging} The populated <code>Paging</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Paging();

            if (data.hasOwnProperty('previous')) {
                obj['previous'] = ApiClient.convertToType(data['previous'], 'String');
            }
            if (data.hasOwnProperty('next')) {
                obj['next'] = ApiClient.convertToType(data['next'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} previous
 */
Paging.prototype['previous'] = undefined;

/**
 * @member {String} next
 */
Paging.prototype['next'] = undefined;






export default Paging;

