/**
 * Lagrello API
 * API specification for Lagrello, a simple to use authentication service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@lagrello.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TotpEnableResponse model module.
 * @module model/TotpEnableResponse
 * @version 1.0.0
 */
class TotpEnableResponse {
    /**
     * Constructs a new <code>TotpEnableResponse</code>.
     * payload with the secret key and url to QR code image
     * @alias module:model/TotpEnableResponse
     * @param secretKey {String} 
     * @param qrImage {String} 
     */
    constructor(secretKey, qrImage) { 
        
        TotpEnableResponse.initialize(this, secretKey, qrImage);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, secretKey, qrImage) { 
        obj['secretKey'] = secretKey;
        obj['qrImage'] = qrImage;
    }

    /**
     * Constructs a <code>TotpEnableResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TotpEnableResponse} obj Optional instance to populate.
     * @return {module:model/TotpEnableResponse} The populated <code>TotpEnableResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TotpEnableResponse();

            if (data.hasOwnProperty('secretKey')) {
                obj['secretKey'] = ApiClient.convertToType(data['secretKey'], 'String');
            }
            if (data.hasOwnProperty('qrImage')) {
                obj['qrImage'] = ApiClient.convertToType(data['qrImage'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} secretKey
 */
TotpEnableResponse.prototype['secretKey'] = undefined;

/**
 * @member {String} qrImage
 */
TotpEnableResponse.prototype['qrImage'] = undefined;






export default TotpEnableResponse;

