/**
 * Lagrello API
 * API specification for Lagrello, a simple to use authentication service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@lagrello.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateTenantRequest model module.
 * @module model/UpdateTenantRequest
 * @version 1.0.0
 */
class UpdateTenantRequest {
    /**
     * Constructs a new <code>UpdateTenantRequest</code>.
     * @alias module:model/UpdateTenantRequest
     */
    constructor() { 
        
        UpdateTenantRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateTenantRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateTenantRequest} obj Optional instance to populate.
     * @return {module:model/UpdateTenantRequest} The populated <code>UpdateTenantRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateTenantRequest();

            if (data.hasOwnProperty('callbackUrl')) {
                obj['callbackUrl'] = ApiClient.convertToType(data['callbackUrl'], 'String');
            }
        }
        return obj;
    }


}

/**
 * This callback address will be used when using the email authentication method. When the end user will have this callback address send to them with the authentication key. In the callback address you need to specify where you want to the auth token to be placed. Specify where in the uri you want to accept the auth token that will then be verified with Lagrello. To specify where you will use these two characters {}.
 * @member {String} callbackUrl
 */
UpdateTenantRequest.prototype['callbackUrl'] = undefined;






export default UpdateTenantRequest;

