/**
 * Lagrello API
 * API specification for Lagrello, a simple to use authentication service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@lagrello.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LagrelloApi);
  }
}(this, function(expect, LagrelloApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LagrelloApi.ActivateTenantRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ActivateTenantRequest', function() {
    it('should create an instance of ActivateTenantRequest', function() {
      // uncomment below and update the code to test ActivateTenantRequest
      //var instane = new LagrelloApi.ActivateTenantRequest();
      //expect(instance).to.be.a(LagrelloApi.ActivateTenantRequest);
    });

    it('should have the property companyName (base name: "companyName")', function() {
      // uncomment below and update the code to test the property companyName
      //var instance = new LagrelloApi.ActivateTenantRequest();
      //expect(instance).to.be();
    });

    it('should have the property companyAddress (base name: "companyAddress")', function() {
      // uncomment below and update the code to test the property companyAddress
      //var instance = new LagrelloApi.ActivateTenantRequest();
      //expect(instance).to.be();
    });

    it('should have the property companyCity (base name: "companyCity")', function() {
      // uncomment below and update the code to test the property companyCity
      //var instance = new LagrelloApi.ActivateTenantRequest();
      //expect(instance).to.be();
    });

    it('should have the property companyPostalCode (base name: "companyPostalCode")', function() {
      // uncomment below and update the code to test the property companyPostalCode
      //var instance = new LagrelloApi.ActivateTenantRequest();
      //expect(instance).to.be();
    });

    it('should have the property companyCountry (base name: "companyCountry")', function() {
      // uncomment below and update the code to test the property companyCountry
      //var instance = new LagrelloApi.ActivateTenantRequest();
      //expect(instance).to.be();
    });

    it('should have the property companyOrgNumber (base name: "companyOrgNumber")', function() {
      // uncomment below and update the code to test the property companyOrgNumber
      //var instance = new LagrelloApi.ActivateTenantRequest();
      //expect(instance).to.be();
    });

    it('should have the property companyVATNumber (base name: "companyVATNumber")', function() {
      // uncomment below and update the code to test the property companyVATNumber
      //var instance = new LagrelloApi.ActivateTenantRequest();
      //expect(instance).to.be();
    });

  });

}));
