/**
 * Lagrello API
 * API specification for Lagrello, a simple to use authentication service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@lagrello.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LagrelloApi);
  }
}(this, function(expect, LagrelloApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LagrelloApi.Tenant();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Tenant', function() {
    it('should create an instance of Tenant', function() {
      // uncomment below and update the code to test Tenant
      //var instane = new LagrelloApi.Tenant();
      //expect(instance).to.be.a(LagrelloApi.Tenant);
    });

    it('should have the property tenantId (base name: "tenantId")', function() {
      // uncomment below and update the code to test the property tenantId
      //var instance = new LagrelloApi.Tenant();
      //expect(instance).to.be();
    });

    it('should have the property tenantName (base name: "tenantName")', function() {
      // uncomment below and update the code to test the property tenantName
      //var instance = new LagrelloApi.Tenant();
      //expect(instance).to.be();
    });

    it('should have the property callbackUrl (base name: "callbackUrl")', function() {
      // uncomment below and update the code to test the property callbackUrl
      //var instance = new LagrelloApi.Tenant();
      //expect(instance).to.be();
    });

    it('should have the property companyInfo (base name: "companyInfo")', function() {
      // uncomment below and update the code to test the property companyInfo
      //var instance = new LagrelloApi.Tenant();
      //expect(instance).to.be();
    });

    it('should have the property activated (base name: "activated")', function() {
      // uncomment below and update the code to test the property activated
      //var instance = new LagrelloApi.Tenant();
      //expect(instance).to.be();
    });

  });

}));
