/**
 * Lagrello API
 * API specification for Lagrello, a simple to use authentication service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@lagrello.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LagrelloApi);
  }
}(this, function(expect, LagrelloApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LagrelloApi.TenantsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TenantsApi', function() {
    describe('tenantUpdate', function() {
      it('should call tenantUpdate successfully', function(done) {
        //uncomment below and update the code to test tenantUpdate
        //instance.tenantUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('tenantsActivate', function() {
      it('should call tenantsActivate successfully', function(done) {
        //uncomment below and update the code to test tenantsActivate
        //instance.tenantsActivate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('tenantsCreate', function() {
      it('should call tenantsCreate successfully', function(done) {
        //uncomment below and update the code to test tenantsCreate
        //instance.tenantsCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('tenantsCreate_0', function() {
      it('should call tenantsCreate_0 successfully', function(done) {
        //uncomment below and update the code to test tenantsCreate_0
        //instance.tenantsCreate_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('tenantsGet', function() {
      it('should call tenantsGet successfully', function(done) {
        //uncomment below and update the code to test tenantsGet
        //instance.tenantsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
